server:
  port: 8091
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/test_mp?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456